services:
  approvalappmonolit:
    image: ${DOCKER_REGISTRY-}approvalappmonolit
    build:
      context: .
      dockerfile: ApprovalAppMonolit/Dockerfile
    ports:
      - "5005:80" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
